# Generated by Django 5.2.7 on 2025-10-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='default-device', max_length=50, unique=True)),
                ('wifi_ssid', models.CharField(default='NomeDaSuaRede', max_length=100)),
                ('wifi_password', models.CharField(default='SuaSenhaAqui', max_length=100)),
                ('start_hour', models.TimeField(default='08:00:00')),
                ('end_hour', models.TimeField(default='18:00:00')),
                ('force_on', models.BooleanField(default=False, verbose_name='Forçar Ventilador Ligado')),
                ('ml_control', models.BooleanField(default=False, verbose_name='Controle por ML')),
                ('ml_duration', models.IntegerField(default=0, verbose_name='Duração recomendada (minutos)')),
                ('ml_start_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FanState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
