# Generated by Django 5.2.7 on 2025-10-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='temperature_limit',
            field=models.FloatField(default=25.0),
        ),
    ]
