# Generated by Django 5.2.7 on 2025-10-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_deviceconfig_temperature_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
