# Generated by Django 5.2.6 on 2025-09-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_fanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='ambienta_esp32_1', max_length=50, unique=True)),
                ('wifi_ssid', models.CharField(default='NomeDaSuaRede', max_length=100)),
                ('wifi_password', models.CharField(default='SuaSenhaAqui', max_length=100)),
                ('start_hour', models.TimeField(default='08:00:00')),
                ('end_hour', models.TimeField(default='18:00:00')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
