# Generated by Django 5.2.6 on 2025-09-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_deviceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconfig',
            name='force_on',
            field=models.BooleanField(default=False, verbose_name='Forçar Ventilador Ligado'),
        ),
    ]
