# Generated by Django 5.2 on 2025-09-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('temperature_prediction', 'Predição de Temperatura'), ('fan_optimization', 'Otimização de Ventilador'), ('anomaly_detection', 'Detecção de Anomalias')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('hyperparameters', models.JSONField(blank=True, default=dict)),
                ('model_file_path', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('model_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField()),
                ('prediction', models.JSONField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_models.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start_date', models.DateTimeField()),
                ('data_end_date', models.DateTimeField()),
                ('training_samples', models.IntegerField()),
                ('validation_samples', models.IntegerField(blank=True, null=True)),
                ('training_metrics', models.JSONField(default=dict)),
                ('validation_metrics', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('running', 'Executando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='ml_models.mlmodel')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_value', models.FloatField()),
                ('evaluation_start', models.DateTimeField()),
                ('evaluation_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='ml_models.mlmodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model', 'metric_name'], name='ml_models_m_model_i_a4e0f5_idx'), models.Index(fields=['created_at'], name='ml_models_m_created_c4e2e3_idx')],
            },
        ),
    ]
