# Generated by Django 5.2.7 on 2025-10-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_alter_trainingsession_model'),
        ('ml_models', '0002_mlmodel_model_data'),
    ]

    operations = [
    ]
